### ISSUE TITLE
Failed to transpile program error 

### ISSUE THREAD

**Issue by francoro** [ionic-team/ionic-app-scripts#1246]
$ ionic cordova build android
[WARN] Detected @ionic/cli-plugin-cordova in your package.json.

       As of CLI 3.8, it is no longer needed. You can uninstall it:

       npm uninstall --save-dev --save-exact @ionic/cli-plugin-cordova

[WARN] Detected @ionic/cli-plugin-ionic-angular in your package.json.

       As of CLI 3.8, it is no longer needed. You can uninstall it:

       npm uninstall --save-dev --save-exact @ionic/cli-plugin-ionic-angular

[INFO] Running app-scripts build: --platform android --target cordova

[15:29:59]  build dev started ...
[15:30:00]  clean started ...
[15:30:00]  clean finished in 3 ms
[15:30:00]  copy started ...
[15:30:00]  transpile started ...
[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 6
            Cannot find name 'describe'.

       L5:  beforeEach(() => {
       L6:    TestBed.configureTestingModule({
       L7:      declarations: [

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 7
            Cannot find name 'beforeEach'.

       L6:  TestBed.configureTestingModule({
       L7:    declarations: [
       L8:      AppComponent

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 16
            Cannot find name 'it'.

      L15:  const fixture = TestBed.createComponent(AppComponent);
      L16:  const app = fixture.debugElement.componentInstance;
      L17:  expect(app).toBeTruthy();

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 19
            Cannot find name 'expect'.

      L18:    }));
      L20:    it(`should have as title 'app works!'`, async(() => {

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 22
            Cannot find name 'it'.

      L21:  const fixture = TestBed.createComponent(AppComponent);
      L22:  const app = fixture.debugElement.componentInstance;
      L23:  expect(app.title).toEqual('app works!');

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 25
            Cannot find name 'expect'.

      L24:    }));
      L26:    it('should render title in a h1 tag', async(() => {

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 28
            Cannot find name 'it'.

      L27:  const fixture = TestBed.createComponent(AppComponent);
      L28:  fixture.detectChanges();
      L29:  const compiled = fixture.debugElement.nativeElement;

[15:30:06]  typescript: C:/Users/NATALIA/Pictures/mdp365-ionic3/src/app/app.component.spec.ts, line: 32
            Cannot find name 'expect'.

      L31:    }));
      L32:  });

Error: Failed to transpile program
    at BuildError.Error (native)
    at new BuildError (C:\Users\NATALIA\Pictures\mdp365-ionic3\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at C:\Users\NATALIA\Pictures\mdp365-ionic3\node_modules\@ionic\app-scripts\dist\transpile.js:137:20
    at transpileWorker (C:\Users\NATALIA\Pictures\mdp365-ionic3\node_modules\@ionic\app-scripts\dist\transpile.js:103:12)
    at Object.transpile (C:\Users\NATALIA\Pictures\mdp365-ionic3\node_modules\@ionic\app-scripts\dist\transpile.js:61:12)
    at buildProject (C:\Users\NATALIA\Pictures\mdp365-ionic3\node_modules\@ionic\app-scripts\dist\build.js:97:78)
    at C:\Users\NATALIA\Pictures\mdp365-ionic3\node_modules\@ionic\app-scripts\dist\build.js:47:16

**Comment by danbucholtz** [comment]
Okay, good catch. We've gotta fix this.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Did this just start breaking in `3.0.0` or is this an old issue? It seems like it just cannot find the types. Make sure you install the `@types/jasmine` package (I think, anyway).

Thanks,
Dan

**Comment by gigocabrera** [comment]
I'm having a somewhat similar issue that started breaking after upgrading to 3.0.0 and ionic-angular 3.7.1. How do you install the @types/jasmine package? Would this help me too?

```

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name '声'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'z'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'ݾ'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'v'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'H'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'y'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'ț'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'X'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'go'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո��[41m/����e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'R0'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'N'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'x3'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D����
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'Y'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  ��e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ�
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'm'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  ?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ��
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'м'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:   \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'l0'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'W'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E�
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'n'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  �ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Left side of comma operator is unused and has no side effects.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  �ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'A'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO�
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'M'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  ]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO���2
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'G'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  ��]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO���2RA��
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'p'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  �]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO���2RA��`�
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 4
            Cannot find name 'Gᳵ'.

�~9�?8l�|����g}1v�-�Ή�kz��N ��o�Y�z��'�z��o���3�o���廘�tƣ��
       L4:  ���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO���2RA��`�q
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 5
            Cannot find name 'Y'.

       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO���2RA��`�qW
                                                                                                                                                                           �% �����!`=�e(Wj�cl�@c)      �<w����W��zU�^����(vJT�N7hɷ�����Q�ͣ�K��?�qe����#r�}�p�:y�-�}��C�E���N��pP��XRĞg�#�Hq��+��njm�&��� ��+�Հl(=
                                                                                                       @���@�/g���������x�`cG>�{3�z�>I"k|MN�2��*pkhα��U�Wd)�4�����-���t���qfp��-~��v�ӓ"�ǹ�
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��
       L6:  ,   �҇�9�I����      8uy�,+��P���3�Z0��S���HB���<sσ<�>n�yp;hy0�_�
                                                                            �sB�

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 5
            The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

       L4:  umm�x�[��Z�~�8|�v���?���i@шո������e?f��0' \Ae���7k�����ǧ��z]�=���]���W�k�̏�����3��S�5�u��=<�v�D�����:�>7��ϱ��}EL1a��aK똆\>wR?)��_Ђ����A/��E��;{sV{FO���2RA��`�qW
                                                                                                                                                                           �% �����!`=�e(Wj�cl�@c)      �<w����W��zU�^����(vJT�N7hɷ�����Q�ͣ�K��?�qe����#r�}�p�:y�-�}��C�E���N��pP��XRĞg�#�Hq��+��njm�&��� ��+�Հl(=
                                                                                                       @���@�/g���������x�`cG>�{3�z�>I"k|MN�2��*pkhα��U�Wd)�4�����-���t���qfp��-~��v�ӓ"�ǹ�
       L5:  �%����6 �Rqr�F�`jBy�@��`@K~��947����$\=�\=La�@?�������_�\8B�st���^  9L�����d����sJ�B4V��pX/����*ΐ��
       L6:  ,   �҇�9�I����      8uy�,+��P���3�Z0��S���HB���<sσ<�>n�yp;hy0�_�
                                                                            �sB�

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 11
            Cannot find name 'ߌ'.

      L10:  * The essential purpose of badge numbers is to enable an application to inform its users that it has something for them — for example, unread messages — when the application isn’t running in the foreground.
      L12:  * Requires Cordova plugin: cordova-plugin-badge. For more info, please see the [Badge plugin docs](https://github.com/katzer/cordova-plugin-badge).

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 11
            Cannot find name 'Av'.

      L10:  * The essential purpose of badge numbers is to enable an application to inform its users that it has something for them — for example, unread messages — when the application isn’t running in the foreground.
      L12:  * Requires Cordova plugin: cordova-plugin-badge. For more info, please see the [Badge plugin docs](https://github.com/katzer/cordova-plugin-badge).

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 11
            Cannot find name 'Lf'.

      L10:  * The essential purpose of badge numbers is to enable an application to inform its users that it has something for them — for example, unread messages — when the application isn’t running in the foreground.
      L12:  * Requires Cordova plugin: cordova-plugin-badge. For more info, please see the [Badge plugin docs](https://github.com/katzer/cordova-plugin-badge).

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 11
            Cannot find name 'N'.

      L10:  * The essential purpose of badge numbers is to enable an application to inform its users that it has something for them — for example, unread messages — when the application isn’t running in the foreground.
      L12:  * Requires Cordova plugin: cordova-plugin-badge. For more info, please see the [Badge plugin docs](https://github.com/katzer/cordova-plugin-badge).

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 14
            Cannot find name 'q'.

      L14:  * @usage
      L15:  * ```typescript

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 14
            Cannot find name 'W'.

      L14:  * @usage
      L15:  * ```typescript

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 14
            Cannot find name 'mnP'.

      L14:  * @usage
      L15:  * ```typescript

[07:08:23]  typescript: node_modules/ionic-native/dist/es5/plugins/badge.d.ts, line: 15
            Cannot find name 'c'.
```

ionic info

```
li packages: (/Users/gigocabrera/Documents/ionic/CajaFuerte/CajaFuerte-app/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-sim : 4.1.1
    Node    : v8.5.0
    npm     : 5.4.2
    OS      : OS X El Capitan
    Xcode   : Xcode 8.2.1 Build version 8C1002

```

**Comment by gigocabrera** [comment]
UPDATE: I ran `npm install --save @types/jasmine` and it didn't fix my problem

**Comment by roccobar** [comment]
same issue here
https://github.com/ionic-team/ionic-app-scripts/issues/1193

**Comment by zdweedle** [comment]
same issue here

**Comment by renatoosousa** [comment]
+1

**Comment by daldantas** [comment]
Same issue.

**Comment by udhaymanhas** [comment]
+1
